const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const { ZipArchive } = require('archiver');
const PDFDocument = require('pdfkit');

function safeName(value) {
  return String(value || 'assembly').replace(/[<>:"/\\|?*\x00-\x1f]/g, '_').slice(0, 120) || 'assembly';
}

function genbankText(name, sequence, fragments = [], annotations = null) {
  const now = new Date();
  const date = `${String(now.getDate()).padStart(2, '0')}-${['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][now.getMonth()]}-${now.getFullYear()}`;
  const sourceAnnotations = Array.isArray(annotations) ? annotations : fragments.map((fragment, index) => {
    const previous = fragments.slice(0, index).reduce((sum, item) => sum + item.sequence.length, 0);
    return { start: previous, end: previous + fragment.sequence.length, type: 'misc_feature', label: fragment.recordName,
      note: `source=${fragment.kind}; left=${fragment.left}; right=${fragment.right}` };
  });
  const features = sourceAnnotations.map((feature) => {
    const type = String(feature.type || 'misc_feature').replace(/\s+/g, '_').slice(0, 15).padEnd(16);
    const qualifiers = [`                     /label="${String(feature.label || '').replace(/"/g, "'")}"`];
    if (feature.color) qualifiers.push(`                     /color="${String(feature.color).replace(/"/g, "'")}"`);
    if (feature.apeInfo) qualifiers.push(`                     /ApEinfo_fwdcolor="${String(feature.apeInfo).replace(/"/g, "'")}"`);
    if (feature.note) qualifiers.push(`                     /note="${String(feature.note).replace(/"/g, "'")}"`);
    return `     ${type}${feature.start + 1}..${feature.end}\n${qualifiers.join('\n')}`;
  }).join('\n');
  const origin = sequence.toLowerCase().match(/.{1,60}/g).map((line, index) => {
    const groups = line.match(/.{1,10}/g).join(' ');
    return `${String(index * 60 + 1).padStart(9)} ${groups}`;
  }).join('\n');
  return `LOCUS       ${safeName(name).slice(0, 16).padEnd(16)} ${String(sequence.length).padStart(11)} bp    DNA     circular SYN ${date}\nDEFINITION  Golden Gate assembly generated by bio-app.\nACCESSION   .\nVERSION     .\nKEYWORDS    .\nSOURCE      synthetic DNA construct\n  ORGANISM  synthetic DNA construct\nFEATURES             Location/Qualifiers\n     source          1..${sequence.length}\n                     /organism="synthetic DNA construct"\n                     /mol_type="other DNA"\n${features}\nORIGIN\n${origin}\n//\n`;
}

function csvEscape(value) {
  const text = String(value ?? '');
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function summaryCsv(result) {
  const rows = [['position','record','type','length','left_overhang','right_overhang']];
  result.fragments.forEach((fragment, index) => rows.push([
    index + 1, fragment.recordName, fragment.kind, fragment.sequence.length, fragment.left, fragment.right,
  ]));
  return rows.map((row) => row.map(csvEscape).join(',')).join('\r\n') + '\r\n';
}

function writePdf(filePath, title, draw) {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ size: 'A4', margin: 42, info: { Title: title } });
    const output = fs.createWriteStream(filePath);
    output.on('finish', resolve);
    output.on('error', reject);
    document.on('error', reject);
    document.pipe(output);
    document.fontSize(18).text(title);
    document.moveDown();
    draw(document);
    document.end();
  });
}

async function writeReports(outputDir, name, result) {
  await fsp.mkdir(outputDir, { recursive: true });
  const base = safeName(name);
  const files = {
    genbank: path.join(outputDir, `${base}.gb`),
    summary: path.join(outputDir, `${base}_summary.csv`),
    report: path.join(outputDir, `${base}.pdf`),
    partsGraph: path.join(outputDir, `${base}_type2s_mix_parts_graph.pdf`),
    connectionsGraph: path.join(outputDir, `${base}_type2s_mix_connections_graph.pdf`),
    warnings: path.join(outputDir, 'warnings.csv'),
    archive: path.join(outputDir, `${base}_assembly_results.zip`),
  };
  await Promise.all([
    fsp.writeFile(files.genbank, genbankText(base, result.sequence, result.fragments, result.features)),
    fsp.writeFile(files.summary, summaryCsv(result)),
    fsp.writeFile(files.warnings, 'message\r\n'),
    writePdf(files.report, `${base} assembly report`, (doc) => {
      doc.fontSize(11).text(`Enzyme: ${result.enzyme}`);
      doc.text(`Construct length: ${result.sequence.length} bp`);
      doc.text(`Input fragments: ${result.fragments.length}`);
      doc.moveDown();
      result.fragments.forEach((item, index) => doc.text(`${index + 1}. ${item.recordName} (${item.kind}, ${item.sequence.length} bp): ${item.left} -> ${item.right}`));
    }),
    writePdf(files.partsGraph, `${base} Type IIS parts graph`, (doc) => {
      const centerX = 297; const centerY = 390; const radius = 175;
      result.fragments.forEach((item, index) => {
        const angle = (Math.PI * 2 * index / result.fragments.length) - Math.PI / 2;
        const x = centerX + Math.cos(angle) * radius;
        const y = centerY + Math.sin(angle) * radius;
        doc.circle(x, y, 24).fillAndStroke('#e9e7ff', '#605bff');
        doc.fillColor('#222').fontSize(8).text(item.recordName, x - 45, y - 5, { width: 90, align: 'center' });
      });
    }),
    writePdf(files.connectionsGraph, `${base} Type IIS connections graph`, (doc) => {
      result.fragments.forEach((item, index) => {
        const next = result.fragments[(index + 1) % result.fragments.length];
        doc.fontSize(11).text(`${item.recordName} --[${item.right}]--> ${next.recordName}`);
      });
    }),
  ]);
  await new Promise((resolve, reject) => {
    const output = fs.createWriteStream(files.archive);
    const archive = new ZipArchive({ zlib: { level: 9 } });
    output.on('close', resolve); output.on('error', reject); archive.on('error', reject);
    archive.pipe(output);
    Object.entries(files).filter(([key]) => key !== 'archive').forEach(([, file]) => archive.file(file, { name: path.basename(file) }));
    archive.finalize();
  });
  return files;
}

module.exports = { genbankText, safeName, summaryCsv, writeReports };
